### ISSUE TITLE
이렇게 짜놓고 워게임이라고 진짜 ;; 개극혐 코드 수준 ㅅㄱ

### ISSUE THREAD

**Issue by hojak99** [tlatkdgus1/wargame#2]

**Comment by tlatkdgus1** [comment]
웹도 못만드는게 까불어 ~! 사실상 수학 못하는 영상처리 프로그래머 ..... 라이브러리충 ....

**Comment by hojak99** [comment]
개소리 나 수학 전교 2등했음;;;; 너랑 수준이 다름 그리고 백엔드 개발 못하면 쉿!

**Comment by tlatkdgus1** [comment]
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz 백엔드 장고는 백 엔드 아닌갑 ? ~!

**Comment by hojak99** [comment]
장고는 좋지만 니가 쓰면;;

**Comment by tlatkdgus1** [comment]
너 근데 파이썬 못 읽잖아....
